#ifndef PROTOCOLL_STATUS_H
#define PROTOCOLL_STATUS_H

#define ASK_ALARM_STATUS 0xA0
#define SEND_ALARM_STATUS 0xA1


#define SKAP_ALARM_INGEN 0xF0
#define SKAP_ALARM_ALARM 0xF1

#define PROTOCOLL_HEADER_SIZE 4

// 6C:79:B8:BB:36:C5


#endif